/*
 * Copyright (C) 2017 Felix Wiemuth
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package felixwiemuth.asyncsim;

/**
 * @author Felix Wiemuth
 */
public class Event implements Comparable<Event> {

    private final long time;
    private final Runnable runnable;

    public Event(long time, Runnable runnable) {
        this.time = time;
        this.runnable = runnable;
    }

    // Generated by Netbeans IDE
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + (int) (this.time ^ (this.time >>> 32));
        return hash;
    }

    // Generated by Netbeans IDE
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Event other = (Event) obj;
        if (this.time != other.time) {
            return false;
        }
        return true;
    }

    @Override
    public int compareTo(Event o) {
        return Long.compare(time, o.time);
    }

    public void run() {
        runnable.run();
    }

    public long getTime() {
        return time;
    }
}
